name: rlbpp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - tqdm
  - jupyter
  - numpy
  - scipy
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - notebook
    - spacy
    - gymnasium
